from database import get_connection

PERSIAN_BOOKS = [
    {
        "id": 90001,
        "title": "سه قطره خون",
        "author": "صادق هدایت",
        "genre": "short-stories, persian-literature, classics",
        "cover_url": "",
        "avg_rating": 4.3,
        "description": "مجموعه داستان‌های کوتاه صادق هدایت که با نگاهی تلخ و طنزآمیز به زندگی، مرگ و رفتار انسان‌ها می‌پردازد.",
    },
    {
        "id": 90002,
        "title": "حاجی‌آقا",
        "author": "صادق هدایت",
        "genre": "fiction, satire, persian-literature",
        "cover_url": "",
        "avg_rating": 3.9,
        "description": "رمانی طنزآمیز از صادق هدایت که چهره‌ای ریاکار و فرصت‌طلب از جامعه ایران را به تصویر می‌کشد.",
    },
    {
        "id": 90003,
        "title": "شازده احتجاب",
        "author": "هوشنگ گلشیری",
        "genre": "fiction, persian-literature, classics",
        "cover_url": "",
        "avg_rating": 4.4,
        "description": "رمانی از هوشنگ گلشیری با روایتی سیال‌ذهن که زوال یک خانواده اشرافی دوران قاجار را روایت می‌کند.",
    },
    {
        "id": 90004,
        "title": "سووشون",
        "author": "سیمین دانشور",
        "genre": "fiction, historical-fiction, persian-literature",
        "cover_url": "",
        "avg_rating": 4.5,
        "description": "رمانی از سیمین دانشور که داستان زنی در شیراز دوران اشغال را در بستر تحولات اجتماعی ایران روایت می‌کند.",
    },
    {
        "id": 90005,
        "title": "سمفونی مردگان",
        "author": "عباس معروفی",
        "genre": "fiction, persian-literature, tragedy",
        "cover_url": "",
        "avg_rating": 4.6,
        "description": "رمانی از عباس معروفی درباره فروپاشی یک خانواده در اردبیل، روایتی از خشونت خانگی و رنج انسانی.",
    },
    {
        "id": 90006,
        "title": "تاریخ مشروطه ایران",
        "author": "احمد کسروی",
        "genre": "history, nonfiction, persian-literature",
        "cover_url": "",
        "avg_rating": 4.0,
        "description": "اثر تاریخی احمد کسروی که رویدادهای انقلاب مشروطه ایران را با نگاهی تحلیلی و دقیق بررسی می‌کند.",
    },
    {
        "id": 90007,
        "title": "کلیدر",
        "author": "محمود دولت‌آبادی",
        "genre": "fiction, persian-literature, classics",
        "cover_url": "",
        "avg_rating": 4.7,
        "description": "رمان حماسی محمود دولت‌آبادی درباره زندگی عشایر خراسان، یکی از بلندترین و شناخته‌شده‌ترین رمان‌های فارسی.",
    },
    {
        "id": 90008,
        "title": "جای خالی سلوچ",
        "author": "محمود دولت‌آبادی",
        "genre": "fiction, persian-literature",
        "cover_url": "",
        "avg_rating": 4.5,
        "description": "رمانی از محمود دولت‌آبادی درباره زنی روستایی که پس از ناپدید شدن همسرش، تنها با فرزندانش دست‌وپنجه نرم می‌کند.",
    },
    {
        "id": 90009,
        "title": "چشم‌هایش",
        "author": "بزرگ علوی",
        "genre": "fiction, persian-literature, romance",
        "cover_url": "",
        "avg_rating": 4.2,
        "description": "رمانی از بزرگ علوی درباره عشق و سیاست در ایران معاصر، روایت‌شده از زبان زنی که عاشق یک نقاش انقلابی است.",
    },
    {
        "id": 90010,
        "title": "تنگسیر",
        "author": "صادق چوبک",
        "genre": "fiction, persian-literature, adventure",
        "cover_url": "",
        "avg_rating": 4.1,
        "description": "رمانی از صادق چوبک درباره مردی در جنوب ایران که برای گرفتن حق خود از ظالمان به پا می‌خیزد.",
    },
    {
        "id": 90011,
        "title": "ملکوت",
        "author": "بهرام صادقی",
        "genre": "fiction, persian-literature, philosophy",
        "cover_url": "",
        "avg_rating": 4.3,
        "description": "رمانی کوتاه و رمزآلود از بهرام صادقی که مرز میان واقعیت و کابوس را به چالش می‌کشد.",
    },
    {
        "id": 90012,
        "title": "بوف کور",
        "author": "صادق هدایت",
        "genre": "fiction, persian-literature, classics, surrealism",
        "cover_url": "",
        "avg_rating": 4.5,
        "description": "شاهکار صادق هدایت و یکی از مهم‌ترین رمان‌های فارسی؛ روایتی سوررئال و روان‌شناختی از عشق، مرگ و توهم.",
    },
    {
        "id": 90013,
        "title": "دایی جان ناپلئون",
        "author": "ایرج پزشک‌زاد",
        "genre": "fiction, satire, persian-literature",
        "cover_url": "",
        "avg_rating": 4.6,
        "description": "رمانی طنزآمیز و محبوب از ایرج پزشک‌زاد که با نگاهی هجوآمیز به جامعه ایران در دوره پهلوی می‌پردازد.",
    },
    {
        "id": 90014,
        "title": "میرامید",
        "author": "امیرحسن چهل‌تن",
        "genre": "fiction, persian-literature, magical-realism",
        "cover_url": "",
        "avg_rating": 4.2,
        "description": "رمانی از امیرحسن چهل‌تن با فضایی رئالیسم جادویی که به زندگی و آرزوهای یک نسل می‌پردازد.",
    },
    {
        "id": 90015,
        "title": "آبشوران",
        "author": "علی‌محمد افغانی",
        "genre": "fiction, persian-literature, social",
        "cover_url": "",
        "avg_rating": 4.1,
        "description": "رمانی از علی‌محمد افغانی درباره زندگی مردم جنوب ایران و کشمکش‌های اجتماعی آنان.",
    },
    {
        "id": 90016,
        "title": "شوهر آهو خانم",
        "author": "علی‌محمد افغانی",
        "genre": "fiction, persian-literature, social",
        "cover_url": "",
        "avg_rating": 4.4,
        "description": "رمانی از علی‌محمد افغانی که به مسائل زنان و زندگی خانوادگی در ایران دهه ۱۳۲۰ می‌پردازد.",
    },
    {
        "id": 90017,
        "title": "گاوخونی",
        "author": "جعفر مدرس صادقی",
        "genre": "fiction, persian-literature, modern",
        "cover_url": "",
        "avg_rating": 4.3,
        "description": "رمانی از جعفر مدرس صادقی با روایتی مدرن و تکه‌تکه که به خاطرات و رویاهای راوی می‌پردازد.",
    },
    {
        "id": 90018,
        "title": "نون والقلم",
        "author": "جلال آل‌احمد",
        "genre": "fiction, persian-literature, satire",
        "cover_url": "",
        "avg_rating": 4.0,
        "description": "رمانی از جلال آل‌احمد که با نگاهی طنزآمیز به دستگاه قضایی و فساد اداری ایران می‌پردازد.",
    },
    {
        "id": 90019,
        "title": "مدیر مدرسه",
        "author": "جلال آل‌احمد",
        "genre": "fiction, persian-literature, social",
        "cover_url": "",
        "avg_rating": 4.2,
        "description": "داستانی از جلال آل‌احمد درباره معلمی که مدیر مدرسه‌ای می‌شود و با مشکلات آموزشی دست‌وپنجه نرم می‌کند.",
    },
    {
        "id": 90020,
        "title": "چمدان",
        "author": "جلال آل‌احمد",
        "genre": "short-stories, persian-literature",
        "cover_url": "",
        "avg_rating": 3.9,
        "description": "مجموعه داستان‌های کوتاه جلال آل‌احمد که به مسائل اجتماعی و سیاسی ایران می‌پردازد.",
    },
    {
        "id": 90021,
        "title": "خروس",
        "author": "ابراهیم گلستان",
        "genre": "short-stories, persian-literature, modern",
        "cover_url": "",
        "avg_rating": 4.1,
        "description": "مجموعه داستان‌های کوتاه ابراهیم گلستان با نثری شاعرانه و تصویری از زندگی مردم جنوب ایران.",
    },
    {
        "id": 90022,
        "title": "اسرار توابین",
        "author": "ابراهیم گلستان",
        "genre": "fiction, persian-literature",
        "cover_url": "",
        "avg_rating": 4.0,
        "description": "داستانی از ابراهیم گلستان که به موضوع عشق و خیانت در بستری اجتماعی می‌پردازد.",
    },
    {
        "id": 90023,
        "title": "کریستین و کید",
        "author": "هوشنگ گلشیری",
        "genre": "fiction, persian-literature, modern",
        "cover_url": "",
        "avg_rating": 4.2,
        "description": "رمانی از هوشنگ گلشیری که با تکنیک‌های روایی مدرن به موضوع عشق و تنهایی می‌پردازد.",
    },
    {
        "id": 90024,
        "title": "آینه‌های دردار",
        "author": "هوشنگ گلشیری",
        "genre": "short-stories, persian-literature",
        "cover_url": "",
        "avg_rating": 4.3,
        "description": "مجموعه داستان‌های کوتاه هوشنگ گلشیری با نگاهی عمیق به روان انسان و جامعه.",
    },
    {
        "id": 90025,
        "title": "معصومیت از دست رفته",
        "author": "رضا براهنی",
        "genre": "fiction, persian-literature, modern",
        "cover_url": "",
        "avg_rating": 4.1,
        "description": "رمانی از رضا براهنی که با زبانی نوآورانه به مسائل اجتماعی و سیاسی ایران می‌پردازد.",
    },
    {
        "id": 90026,
        "title": "آواز کشتگان",
        "author": "رضا براهنی",
        "genre": "fiction, persian-literature, political",
        "cover_url": "",
        "avg_rating": 4.4,
        "description": "رمانی از رضا براهنی درباره سرکوب و شکنجه در زندان‌های سیاسی ایران.",
    },
    {
        "id": 90027,
        "title": "رازهای سرزمین من",
        "author": "رضا براهنی",
        "genre": "fiction, persian-literature, historical",
        "cover_url": "",
        "avg_rating": 4.2,
        "description": "رمانی از رضا براهنی که به تاریخ معاصر ایران و تحولات سیاسی آن می‌پردازد.",
    },
    {
        "id": 90028,
        "title": "زوال کلنل",
        "author": "محمود دولت‌آبادی",
        "genre": "fiction, persian-literature",
        "cover_url": "",
        "avg_rating": 4.3,
        "description": "رمانی از محمود دولت‌آبادی درباره یک افسر ارتش که پس از کودتای ۲۸ مرداد دچار فروپاشی روحی می‌شود.",
    },
    {
        "id": 90029,
        "title": "روزگار سپری‌شده مردم سالخورده",
        "author": "محمود دولت‌آبادی",
        "genre": "fiction, persian-literature, historical",
        "cover_url": "",
        "avg_rating": 4.5,
        "description": "رمانی از محمود دولت‌آبادی که به تاریخ معاصر ایران از دید یک خانواده می‌پردازد.",
    },
    {
        "id": 90030,
        "title": "سفر به گرای ۲۷۰ درجه",
        "author": "احمد دهقان",
        "genre": "fiction, war-fiction, persian-literature",
        "cover_url": "",
        "avg_rating": 4.3,
        "description": "رمانی از احمد دهقان درباره جنگ ایران و عراق، روایتی از جوانی که به جبهه می‌رود.",
    },
    {
        "id": 90031,
        "title": "نخل‌های سوخته",
        "author": "قاسم‌علی فراست",
        "genre": "fiction, war-fiction, persian-literature",
        "cover_url": "",
        "avg_rating": 4.0,
        "description": "مجموعه داستان‌های کوتاه از قاسم‌علی فراست درباره جنگ و تأثیرات آن بر زندگی مردم.",
    },
    {
        "id": 90032,
        "title": "دختر شینا",
        "author": "بهناز ضرابی‌زاده",
        "genre": "nonfiction, memoir, persian-literature",
        "cover_url": "",
        "avg_rating": 4.4,
        "description": "خاطرات همسر شهید ستار ابراهیمی، روایتی از زندگی زنان در دوران جنگ ایران و عراق.",
    },
    {
        "id": 90033,
        "title": "دا",
        "author": "زهرا حسینی",
        "genre": "nonfiction, memoir, war",
        "cover_url": "",
        "avg_rating": 4.7,
        "description": "خاطرات زهرا حسینی از روزهای جنگ و مقاومت مردم خرمشهر، یکی از پرفروش‌ترین کتاب‌های خاطرات جنگ.",
    },
    {
        "id": 90034,
        "title": "پایی که جا ماند",
        "author": "سید ناصر حسینی‌پور",
        "genre": "nonfiction, memoir, war",
        "cover_url": "",
        "avg_rating": 4.6,
        "description": "خاطرات اسارت سید ناصر حسینی‌پور در زندان‌های عراق، روایتی تکان‌دهنده از مقاومت و رنج.",
    },
    {
        "id": 90035,
        "title": "سلام بر ابراهیم",
        "author": "گروه فرهنگی شهید ابراهیم هادی",
        "genre": "nonfiction, biography, war",
        "cover_url": "",
        "avg_rating": 4.5,
        "description": "زندگینامه شهید ابراهیم هادی، روایتی از جوانمردی و فداکاری در دوران جنگ.",
    },
    {
        "id": 90036,
        "title": "خاطرات یک مترجم",
        "author": "حسن شهیدی",
        "genre": "nonfiction, memoir, persian-literature",
        "cover_url": "",
        "avg_rating": 4.1,
        "description": "خاطرات حسن شهیدی، مترجم و نویسنده ایرانی، از زندگی و کار در ایران و خارج از کشور.",
    },
    {
        "id": 90037,
        "title": "از چیزهای دیگر",
        "author": "محمدعلی موحد",
        "genre": "nonfiction, essays, persian-literature",
        "cover_url": "",
        "avg_rating": 4.3,
        "description": "مجموعه مقالات و یادداشت‌های محمدعلی موحد درباره تاریخ، ادبیات و فرهنگ ایران.",
    },
    {
        "id": 90038,
        "title": "خواب آشفته نفت",
        "author": "محمدعلی موحد",
        "genre": "nonfiction, history, persian-literature",
        "cover_url": "",
        "avg_rating": 4.4,
        "description": "تحلیلی از تاریخ نفت در ایران و نقش آن در سیاست و اقتصاد کشور.",
    },
    {
        "id": 90039,
        "title": "تاریخ ایران باستان",
        "author": "حسن پیرنیا",
        "genre": "history, nonfiction, persian-literature",
        "cover_url": "",
        "avg_rating": 4.2,
        "description": "اثر کلاسیک حسن پیرنیا درباره تاریخ ایران از دوران هخامنشیان تا پایان ساسانیان.",
    },
    {
        "id": 90040,
        "title": "تاریخ تمدن ایران ساسانی",
        "author": "شاپور شهبازی",
        "genre": "history, nonfiction, persian-literature",
        "cover_url": "",
        "avg_rating": 4.3,
        "description": "پژوهشی از شاپور شهبازی درباره تمدن و فرهنگ ایران در دوران ساسانی.",
    },
    {
        "id": 90041,
        "title": "ایران بین دو انقلاب",
        "author": "یرواند آبراهامیان",
        "genre": "history, nonfiction, political",
        "cover_url": "",
        "avg_rating": 4.5,
        "description": "تحلیلی از تاریخ سیاسی ایران از انقلاب مشروطه تا انقلاب اسلامی، اثر یرواند آبراهامیان.",
    },
    {
        "id": 90042,
        "title": "کتاب اعترافات",
        "author": "ژان-ژاک روسو",
        "genre": "nonfiction, memoir, philosophy",
        "cover_url": "",
        "avg_rating": 4.1,
        "description": "ترجمه فارسی اعترافات ژان-ژاک روسو، یکی از مهم‌ترین کتاب‌های زندگی‌نامه‌ای جهان.",
    },
    {
        "id": 90043,
        "title": "قلعه حیوانات",
        "author": "جورج اورول",
        "genre": "fiction, political-satire, classics",
        "cover_url": "",
        "avg_rating": 4.6,
        "description": "ترجمه فارسی قلعه حیوانات جورج اورول، تمثیلی سیاسی درباره قدرت و فساد.",
    },
    {
        "id": 90044,
        "title": "۱۹۸۴",
        "author": "جورج اورول",
        "genre": "fiction, dystopian, classics",
        "cover_url": "",
        "avg_rating": 4.7,
        "description": "ترجمه فارسی ۱۹۸۴ جورج اورول، رمانی دیستوپیایی درباره نظارت و سرکوب.",
    },
    {
        "id": 90045,
        "title": "صد سال تنهایی",
        "author": "گابریل گارسیا مارکز",
        "genre": "fiction, magical-realism, classics",
        "cover_url": "",
        "avg_rating": 4.6,
        "description": "ترجمه فارسی صد سال تنهایی گابریل گارسیا مارکز، شاهکار رئالیسم جادویی.",
    },
    {
        "id": 90046,
        "title": "عشق سال‌های وبا",
        "author": "گابریل گارسیا مارکز",
        "genre": "fiction, romance, magical-realism",
        "cover_url": "",
        "avg_rating": 4.4,
        "description": "ترجمه فارسی عشق سال‌های وبا، رمانی از مارکز درباره عشقی که یک عمر انتظار می‌کشد.",
    },
    {
        "id": 90047,
        "title": "کیمیاگر",
        "author": "پائولو کوئیلو",
        "genre": "fiction, philosophy, inspirational",
        "cover_url": "",
        "avg_rating": 4.2,
        "description": "ترجمه فارسی کیمیاگر پائولو کوئیلو، داستانی درباره رویاها و دنبال کردن سرنوشت.",
    },
    {
        "id": 90048,
        "title": "ملت عشق",
        "author": "الیف شافاک",
        "genre": "fiction, historical-fiction, romance",
        "cover_url": "",
        "avg_rating": 4.5,
        "description": "ترجمه فارسی ملت عشق الیف شافاک، رمانی درباره شمس و مولانا و عشق الهی.",
    },
    {
        "id": 90049,
        "title": "جزء از کل",
        "author": "استیو تولتز",
        "genre": "fiction, humor, contemporary",
        "cover_url": "",
        "avg_rating": 4.4,
        "description": "ترجمه فارسی جزء از کل استیو تولتز، رمانی پرکشش درباره خانواده و رازهای آن.",
    },
    {
        "id": 90050,
        "title": "انسان در جستجوی معنا",
        "author": "ویکتور فرانکل",
        "genre": "nonfiction, psychology, philosophy",
        "cover_url": "",
        "avg_rating": 4.7,
        "description": "ترجمه فارسی انسان در جستجوی معنا ویکتور فرانکل، روایتی از زندگی در اردوگاه‌های نازی و معنای زندگی.",
    },
    {
        "id": 90051,
        "title": "دیوان حافظ",
        "author": "حافظ شیرازی",
        "genre": "poetry, persian-literature, classics",
        "cover_url": "",
        "avg_rating": 4.9,
        "description": "دیوان اشعار حافظ شیرازی، یکی از مهم‌ترین آثار ادبیات فارسی و جهان.",
    },
    {
        "id": 90052,
        "title": "مثنوی معنوی",
        "author": "مولانا جلال‌الدین رومی",
        "genre": "poetry, persian-literature, mysticism",
        "cover_url": "",
        "avg_rating": 4.9,
        "description": "مثنوی معنوی مولانا، شاهکار عرفان و ادبیات فارسی در شش دفتر.",
    },
    {
        "id": 90053,
        "title": "گلستان",
        "author": "سعدی شیرازی",
        "genre": "poetry, persian-literature, classics",
        "cover_url": "",
        "avg_rating": 4.8,
        "description": "گلستان سعدی، مجموعه حکایت‌ها و اشعار اخلاقی و عرفانی به نثر مسجع.",
    },
    {
        "id": 90054,
        "title": "بوستان",
        "author": "سعدی شیرازی",
        "genre": "poetry, persian-literature, classics",
        "cover_url": "",
        "avg_rating": 4.7,
        "description": "بوستان سعدی، مثنوی اخلاقی و عرفانی در ده باب.",
    },
    {
        "id": 90055,
        "title": "شاهنامه",
        "author": "فردوسی",
        "genre": "poetry, epic, persian-literature",
        "cover_url": "",
        "avg_rating": 4.9,
        "description": "شاهنامه فردوسی، حماسه ملی ایران و یکی از بزرگ‌ترین آثار ادبی جهان.",
    },
    {
        "id": 90056,
        "title": "خمسه",
        "author": "نظامی گنجوی",
        "genre": "poetry, persian-literature, classics",
        "cover_url": "",
        "avg_rating": 4.8,
        "description": "خمسه نظامی گنجوی، شامل پنج مثنوی معروف از جمله لیلی و مجنون و خسرو و شیرین.",
    },
    {
        "id": 90057,
        "title": "لیلی و مجنون",
        "author": "نظامی گنجوی",
        "genre": "poetry, romance, persian-literature",
        "cover_url": "",
        "avg_rating": 4.7,
        "description": "لیلی و مجنون نظامی گنجوی، داستان عشق افسانه‌ای که به یکی از شاهکارهای ادبیات فارسی تبدیل شد.",
    },
    {
        "id": 90058,
        "title": "خسرو و شیرین",
        "author": "نظامی گنجوی",
        "genre": "poetry, romance, persian-literature",
        "cover_url": "",
        "avg_rating": 4.7,
        "description": "خسرو و شیرین نظامی گنجوی، داستان عشق خسرو پرویز و شیرین.",
    },
    {
        "id": 90059,
        "title": "منطق‌الطیر",
        "author": "عطار نیشابوری",
        "genre": "poetry, mysticism, persian-literature",
        "cover_url": "",
        "avg_rating": 4.8,
        "description": "منطق‌الطیر عطار نیشابوری، مثنوی عرفانی درباره سفر پرندگان به سوی سیمرغ.",
    },
    {
        "id": 90060,
        "title": "تذکرة الاولیا",
        "author": "عطار نیشابوری",
        "genre": "nonfiction, mysticism, persian-literature",
        "cover_url": "",
        "avg_rating": 4.6,
        "description": "تذکرة الاولیا عطار، شرح حال عارفان و صوفیان بزرگ اسلامی.",
    },
    {
        "id": 90061,
        "title": "مصیبت‌نامه",
        "author": "عطار نیشابوری",
        "genre": "poetry, mysticism, persian-literature",
        "cover_url": "",
        "avg_rating": 4.5,
        "description": "مصیبت‌نامه عطار، مثنوی عرفانی درباره رنج و مصیبت‌های انسانی.",
    },
    {
        "id": 90062,
        "title": "دیوان شمس",
        "author": "مولانا جلال‌الدین رومی",
        "genre": "poetry, mysticism, persian-literature",
        "cover_url": "",
        "avg_rating": 4.8,
        "description": "دیوان شمس مولانا، مجموعه غزلیات عاشقانه و عرفانی.",
    },
    {
        "id": 90063,
        "title": "فیه ما فیه",
        "author": "مولانا جلال‌الدین رومی",
        "genre": "nonfiction, mysticism, persian-literature",
        "cover_url": "",
        "avg_rating": 4.6,
        "description": "فیه ما فیه مولانا، مجموعه سخنرانی‌ها و مجالس او درباره عرفان و تصوف.",
    },
    {
        "id": 90064,
        "title": "مکتوبات",
        "author": "مولانا جلال‌الدین رومی",
        "genre": "nonfiction, mysticism, persian-literature",
        "cover_url": "",
        "avg_rating": 4.4,
        "description": "مکتوبات مولانا، نامه‌های او به دوستان و مریدان.",
    },
    {
        "id": 90065,
        "title": "حدیقه الحقیقه",
        "author": "سنایی غزنوی",
        "genre": "poetry, mysticism, persian-literature",
        "cover_url": "",
        "avg_rating": 4.5,
        "description": "حدیقه الحقیقه سنایی، مثنوی عرفانی و اخلاقی.",
    },
    {
        "id": 90066,
        "title": "مخزن‌الاسرار",
        "author": "نظامی گنجوی",
        "genre": "poetry, mysticism, persian-literature",
        "cover_url": "",
        "avg_rating": 4.5,
        "description": "مخزن‌الاسرار نظامی، مثنوی عرفانی و اخلاقی.",
    },
    {
        "id": 90067,
        "title": "ویس و رامین",
        "author": "فخرالدین اسعد گرگانی",
        "genre": "poetry, romance, persian-literature",
        "cover_url": "",
        "avg_rating": 4.4,
        "description": "ویس و رامین، داستان عاشقانه کهن فارسی از فخرالدین اسعد گرگانی.",
    },
    {
        "id": 90068,
        "title": "کلیله و دمنه",
        "author": "نصرالله منشی",
        "genre": "fiction, fable, persian-literature",
        "cover_url": "",
        "avg_rating": 4.6,
        "description": "کلیله و دمنه، ترجمه نصرالله منشی از مجموعه حکایت‌های حیوانات با مضامین اخلاقی.",
    },
    {
        "id": 90069,
        "title": "تاریخ بیهقی",
        "author": "ابوالفضل بیهقی",
        "genre": "history, nonfiction, persian-literature",
        "cover_url": "",
        "avg_rating": 4.7,
        "description": "تاریخ بیهقی، اثر ابوالفضل بیهقی درباره تاریخ غزنویان، یکی از شاهکارهای نثر فارسی.",
    },
    {
        "id": 90070,
        "title": "سیاست‌نامه",
        "author": "خواجه نظام‌الملک طوسی",
        "genre": "nonfiction, political, persian-literature",
        "cover_url": "",
        "avg_rating": 4.5,
        "description": "سیاست‌نامه خواجه نظام‌الملک، رساله‌ای درباره کشورداری و سیاست در دوران سلجوقیان.",
    },
    {
        "id": 90071,
        "title": "قابوس‌نامه",
        "author": "عنصرالمعالی کیکاوس",
        "genre": "nonfiction, ethics, persian-literature",
        "cover_url": "",
        "avg_rating": 4.4,
        "description": "قابوس‌نامه، پندنامه‌ای از عنصرالمعالی به فرزندش درباره اخلاق و زندگی.",
    },
    {
        "id": 90072,
        "title": "اخلاق ناصری",
        "author": "خواجه نصیرالدین طوسی",
        "genre": "nonfiction, philosophy, persian-literature",
        "cover_url": "",
        "avg_rating": 4.5,
        "description": "اخلاق ناصری خواجه نصیرالدین طوسی، اثری درباره فلسفه اخلاق و حکمت عملی.",
    },
    {
        "id": 90073,
        "title": "اسرارالتوحید",
        "author": "محمد بن منور",
        "genre": "nonfiction, mysticism, persian-literature",
        "cover_url": "",
        "avg_rating": 4.6,
        "description": "اسرارالتوحید، شرح حال ابوسعید ابوالخیر، عارف نامدار ایرانی.",
    },
    {
        "id": 90074,
        "title": "کشف‌المحجوب",
        "author": "علی بن عثمان هجویری",
        "genre": "nonfiction, mysticism, persian-literature",
        "cover_url": "",
        "avg_rating": 4.5,
        "description": "کشف‌المحجوب هجویری، یکی از قدیمی‌ترین متون عرفانی فارسی.",
    },
    {
        "id": 90075,
        "title": "رساله قشیریه",
        "author": "عبدالکریم قشیری",
        "genre": "nonfiction, mysticism, persian-literature",
        "cover_url": "",
        "avg_rating": 4.4,
        "description": "رساله قشیریه، اثری درباره تصوف و عرفان اسلامی.",
    },
]


def seed_persian_books():
    conn = get_connection()
    cursor = conn.cursor()

    rows = [
        (
            b["id"], b["title"], b["author"], b["genre"],
            b["cover_url"], b["avg_rating"], b["description"]
        )
        for b in PERSIAN_BOOKS
    ]

    cursor.executemany(
        """INSERT OR REPLACE INTO books
           (id, title, author, genre, cover_url, avg_rating, description)
           VALUES (?, ?, ?, ?, ?, ?, ?)""",
        rows
    )

    conn.commit()
    conn.close()
    print(f"Seeded {len(rows)} Persian books.")


if __name__ == "__main__":
    seed_persian_books()