from database import get_connection

PERSIAN_BOOKS = [
    {
        "id": 90001,
        "title": "سه قطره خون",
        "author": "صادق هدایت",
        "genre": "short-stories, persian-literature, classics",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327885442i/6557601.jpg",
        "avg_rating": 4.3,
        "description": "مجموعه‌ای باشکوه و در عین حال تیره از داستان‌های کوتاه صادق هدایت که در آن‌ها مرز میان جنون، واقعیت، مرگ و آرزوهای بربادرفته به‌زیبایی در هم می‌آمیزد.",
    },
    {
        "id": 90002,
        "title": "حاجی‌آقا",
        "author": "صادق هدایت",
        "genre": "fiction, satire, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1235122171i/3431604.jpg",
        "avg_rating": 3.9,
        "description": "رمانی سیاسی-اجتماعی و طنزآمیز از صادق هدایت که پرده از ریاکاری، معامله‌گری سیاسی و فرصت‌طلبی یکی از رجال سرشناس تهران در سال‌های جنگ جهانی دوم برمی‌دارد.",
    },
    {
        "id": 90003,
        "title": "شازده احتجاب",
        "author": "هوشنگ گلشیری",
        "genre": "fiction, persian-literature, classics",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918385i/3229670.jpg",
        "avg_rating": 4.4,
        "description": "شاهکار تکنیکی هوشنگ گلشیری با روایتی سیال‌ذهن که در شب نهایی زندگی آخرین شازده قاجار گذر کرده و زوال، استبداد خانوادگی و فروپاشی یک سلسله را تجسم می‌بخشد.",
    },
    {
        "id": 90004,
        "title": "سووشون",
        "author": "سیمین دانشور",
        "genre": "fiction, historical-fiction, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327869680i/1858718.jpg",
        "avg_rating": 4.5,
        "description": "نخستین رمان برجسته نویسنده زن ایرانی، سیمین دانشور؛ روایتی عمیق و پرکشش از زندگی «زری» در شیرازِ زیر اشغال نیروهای انگلیسی در جنگ جهانی دوم و مقاومت و آزادگی.",
    },
    {
        "id": 90005,
        "title": "سمفونی مردگان",
        "author": "عباس معروفی",
        "genre": "fiction, persian-literature, tragedy",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327868770i/6098048.jpg",
        "avg_rating": 4.6,
        "description": "شاهکار حماسی و تراژیک عباس معروفی که در چهار موومان به سبک موسیقی کلاسیک روایت می‌شود و داستان برادركشی، سرکوب استعداد و فروپاشی خانواده اورخانی در اردبیل را بازگو می‌کند.",
    },
    {
        "id": 90006,
        "title": "تاریخ مشروطه ایران",
        "author": "احمد کسروی",
        "genre": "history, nonfiction, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388836587i/1284501.jpg",
        "avg_rating": 4.0,
        "description": "مهم‌ترین و مستندترین منبع تاریخی درباره انقلاب مشروطیت ایران که احمد کسروی با دقت علمی، مشاهده مستقیم و تحلیل اجتماعی دقیق آن را به نگارش درآورده است.",
    },
    {
        "id": 90007,
        "title": "کلیدر",
        "author": "محمود دولت‌آبادی",
        "genre": "fiction, persian-literature, classics",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918389i/1653896.jpg",
        "avg_rating": 4.7,
        "description": "حماسه بی‌نظیر ۱۰ جلدی محمود دولت‌آبادی درباره زندگی عشایر سبزوار و سرگذشت گل‌محمد؛ رمانی پرشکوه که فرهنگ، زبان، رنج و مبارزه روستاییان خراسان را به تصویر می‌کشد.",
    },
    {
        "id": 90008,
        "title": "جای خالی سلوچ",
        "author": "محمود دولت‌آبادی",
        "genre": "fiction, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918388i/2274485.jpg",
        "avg_rating": 4.5,
        "description": "رمانی اثرگذار از محمود دولت‌آبادی درباره زنی شجاع به نام مرگان که پس از ناپدید شدن ناگهانی همسرش سلوچ، در روستایی محروم برای حفظ خانواده‌اش دست به جهادی خاموش می‌زند.",
    },
    {
        "id": 90009,
        "title": "چشم‌هایش",
        "author": "بزرگ علوی",
        "genre": "fiction, persian-literature, romance",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918386i/2274483.jpg",
        "avg_rating": 4.2,
        "description": "رمانی معماگونه و عاشقانه-سیاسی از بزرگ علوی که راز پرتره زنی با چشم‌های مرموز را رازگشایی کرده و مبارزات سیاسی دوران رضاخان را با عشقی ناکام پیوند می‌دهد.",
    },
    {
        "id": 90010,
        "title": "تنگسیر",
        "author": "صادق چوبک",
        "genre": "fiction, persian-literature, adventure",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918387i/2274484.jpg",
        "avg_rating": 4.1,
        "description": "داستان شجاعت و انتقام‌جویی زارمحمد (شیرمحمد) در بوشهر که پس از غارت دارایی‌اش توسط متنفذین شهری، خود به تنهایی برای گرفتن داد خویش به پا می‌خیزد.",
    },
    {
        "id": 90011,
        "title": "ملکوت",
        "author": "بهرام صادقی",
        "genre": "fiction, persian-literature, philosophy",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918390i/2274486.jpg",
        "avg_rating": 4.3,
        "description": "داستانی بلند و فشرده از بهرام صادقی با فضایی گوتیک و نمادین که با حلول جن در آقای مودت آغاز شده و به کاوش در مفهوم حلول شر، مرگ و پوچی وجود می‌پردازد.",
    },
    {
        "id": 90012,
        "title": "بوف کور",
        "author": "صادق هدایت",
        "genre": "fiction, persian-literature, classics, surrealism",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1247072522i/6557608.jpg",
        "avg_rating": 4.5,
        "description": "قله ادبیات مدرن ایران و شاهکار سوررئالیستی صادق هدایت؛ روایتی روان‌شناختی، تاریک و کابوس‌وار از راوی انزواطلبی که لایه‌های پنهان روان، زن اثیری و مرگ را می‌کاود.",
    },
    {
        "id": 90013,
        "title": "دایی جان ناپلئون",
        "author": "ایرج پزشک‌زاد",
        "genre": "fiction, satire, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327871638i/820713.jpg",
        "avg_rating": 4.6,
        "description": "محبوب‌ترین رمان طنز ادبیات فارسی درباره خيل عجیب و غریب یک خانواده اشرافی در تهران قدیم، توهم تآمر انگلیسی‌ها توسط دایی‌جان و روایت شادمانه اولین عشق نوجوانی.",
    },
    {
        "id": 90014,
        "title": "میرامید",
        "author": "امیرحسن چهل‌تن",
        "genre": "fiction, persian-literature, magical-realism",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388836588i/6098050.jpg",
        "avg_rating": 4.2,
        "description": "رمانی جالب با تلفیقی از واقعیت تاریخی و رئالیسم جادویی که زیست و سرنوشت طبقه‌ای از جامعه معاصر را در بستری از باورها و اسطوره‌های ایرانی می‌کاود.",
    },
    {
        "id": 90015,
        "title": "آبشوران",
        "author": "علی‌محمد افغانی",
        "genre": "fiction, persian-literature, social",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388836589i/6098051.jpg",
        "avg_rating": 4.1,
        "description": "مجموعه‌داستانی رئالیستی و افشاگر از علی‌محمد افغانی که با دقت زیاد و توصیف‌های قوی به فقر، رنج و مناسبات اجتماعی طبقات محروم جامعه می‌پردازد.",
    },
    {
        "id": 90016,
        "title": "شوهر آهو خانم",
        "author": "علی‌محمد افغانی",
        "genre": "fiction, persian-literature, social",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918391i/2274487.jpg",
        "avg_rating": 4.4,
        "description": "رمان جریان‌ساز و سترگ علی‌محمد افغانی درباره جامعه سنت‌زده دهه ۱۳۱۰، چندهمسری و تقابل صبر زنانه «آهو» با هوس‌رانی «سیدمیران» و ورود زن جدید به خانه.",
    },
    {
        "id": 90017,
        "title": "گاوخونی",
        "author": "جعفر مدرس صادقی",
        "genre": "fiction, persian-literature, modern",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388836590i/2274488.jpg",
        "avg_rating": 4.3,
        "description": "رمانی مدرن، مینیمال و رویابافته که با روایتی کابوس‌گونه خاطرات زاینده‌رود، رویاهای جوانی در تهران و رابطه گنگ پدر و پسری را درهم می‌آمیزد.",
    },
    {
        "id": 90018,
        "title": "نون والقلم",
        "author": "جلال آل‌احمد",
        "genre": "fiction, persian-literature, satire",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388836591i/2274489.jpg",
        "avg_rating": 4.0,
        "description": "داستانی تاریخی-تمثیلی با لحن طنز و نقد اجتماعی از جلال آل‌احمد که سرنوشت دو میرزا و کاتب را در جریان یک نهضت مردمی و شکست آن روایت می‌کند.",
    },
    {
        "id": 90019,
        "title": "مدیر مدرسه",
        "author": "جلال آل‌احمد",
        "genre": "fiction, persian-literature, social",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918392i/2274490.jpg",
        "avg_rating": 4.2,
        "description": "روایت صریح و انتقادی جلال آل‌احمد از زبان آموزگاری که برای فرار از تدریس، مدیریت مدرسه‌ای پرت افتاده را می‌پذیرد اما با فساد سیستم آموزشی روبرو می‌شود.",
    },
    {
        "id": 90020,
        "title": "چمدان",
        "author": "جلال آل‌احمد",
        "genre": "short-stories, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388836592i/2274491.jpg",
        "avg_rating": 3.9,
        "description": "نخستین مجموعه داستان کوتاه جلال آل‌احمد شامل ۶ داستان روان و پرنکته که طبقات مختلف جامعه ایران در دهه ۱۳۲۰ را با نقد اجتماعی تحلیلی ترسیم می‌کند.",
    },
    {
        "id": 90021,
        "title": "خروس",
        "author": "ابراهیم گلستان",
        "genre": "short-stories, persian-literature, modern",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388836593i/2274492.jpg",
        "avg_rating": 4.1,
        "description": "قصه‌ای نمادین و استعاری با نثر آهنگین و بی‌نظیر ابراهیم گلستان که در بندری جنوبی می‌گذرد و بانگ خروس و جهل اهالی را به نقد می‌کشد.",
    },
    {
        "id": 90022,
        "title": "اسرار توابین",
        "author": "ابراهیم گلستان",
        "genre": "fiction, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388836594i/2274493.jpg",
        "avg_rating": 4.0,
        "description": "اثر داستانی دغدغه‌مند از ابراهیم گلستان با فرم و زبانی فاخر که به لایه‌های روان‌شناختی تحولات فکری و پشیمانی‌های عقیدتی در بستر جامعه می‌پردازد.",
    },
    {
        "id": 90023,
        "title": "کریستین و کید",
        "author": "هوشنگ گلشیری",
        "genre": "fiction, persian-literature, modern",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388836595i/2274494.jpg",
        "avg_rating": 4.2,
        "description": "روایتی مدرن و چندلایه از هوشنگ گلشیری که به فرم، ساختار داستان‌نویسی، تنهایی انسان معاصر و روابط عاطفی در فضایی روشن‌فکرانه می‌پردازد.",
    },
    {
        "id": 90024,
        "title": "آینه‌های دردار",
        "author": "هوشنگ گلشیری",
        "genre": "short-stories, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388836596i/2274495.jpg",
        "avg_rating": 4.3,
        "description": "رمانی از هوشنگ گلشیری درباره سفر نویسنده‌ای ایرانی به شهرهای اروپا برای داستان‌خوانی؛ کاوشی عمیق در هویت، غربت، خاطره و آینه‌های روحی.",
    },
    {
        "id": 90025,
        "title": "معصومیت از دست رفته",
        "author": "رضا براهنی",
        "genre": "fiction, persian-literature, modern",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388836597i/2274496.jpg",
        "avg_rating": 4.1,
        "description": "رمانی جسورانه از رضا براهنی با تکنیک‌های روایی نوپدید که به دغدغه‌های سیاسی، ناعدالتی اجتماعی و از بین رفتن پاکی‌های انسانی نگاهی انتقادی دارد.",
    },
    {
        "id": 90026,
        "title": "آواز کشتگان",
        "author": "رضا براهنی",
        "genre": "fiction, persian-literature, political",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388836598i/2274497.jpg",
        "avg_rating": 4.4,
        "description": "رمانی افشاگر و تلخ از رضا براهنی که فضای اختناق، شکنجه، سرکوب دانشگاهیان و مبارزات سیاسی پیش از انقلاب ۵۷ را به تصویر می‌کشد.",
    },
    {
        "id": 90027,
        "title": "رازهای سرزمین من",
        "author": "رضا براهنی",
        "genre": "fiction, persian-literature, historical",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388836599i/2274498.jpg",
        "avg_rating": 4.2,
        "description": "رمان دو جلدی و مفصل رضا براهنی؛ حماسه‌ای از تاریخ معاصر ایران از کودتای ۲۸ مرداد تا انقلاب اسلامی که لایه‌های پنهان قدرت و اجتماع را تحلیل می‌کند.",
    },
    {
        "id": 90028,
        "title": "زوال کلنل",
        "author": "محمود دولت‌آبادی",
        "genre": "fiction, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1335345781i/13624831.jpg",
        "avg_rating": 4.3,
        "description": "رمانی تکان‌دهنده از محمود دولت‌آبادی درباره یک کلنل سابق ارتش شاهنشاهی که در شبی بارانی باید فرزاندان قربانی‌شده‌اش در جریانات سیاسی را به خاک بسپارد.",
    },
    {
        "id": 90029,
        "title": "روزگار سپری‌شده مردم سالخورده",
        "author": "محمود دولت‌آبادی",
        "genre": "fiction, persian-literature, historical",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388836600i/2274499.jpg",
        "avg_rating": 4.5,
        "description": "سه‌گانه‌ای باارزش از محمود دولت‌آبادی که در سیر زمان به تغییرات تاریخی، طبقاتی و فرهنگی روستای تلخ‌آباد و مردمانش می‌پردازد.",
    },
    {
        "id": 90030,
        "title": "سفر به گرای ۲۷۰ درجه",
        "author": "احمد دهقان",
        "genre": "fiction, war-fiction, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388836601i/2274500.jpg",
        "avg_rating": 4.3,
        "description": "رمانی واقعی و بدون شعار از احمد دهقان درباره جنگ ایران و عراق؛ روایتی عاری از اغراق از تجربیات دانش‌آموزی رزمنده در عملیات کربلای ۵.",
    },
    {
        "id": 90031,
        "title": "نخل‌های سوخته",
        "author": "قاسم‌علی فراست",
        "genre": "fiction, war-fiction, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388836602i/2274501.jpg",
        "avg_rating": 4.0,
        "description": "مجموعه‌ای از داستان‌های ملموس درباره آغاز جنگ تحمیلی در مناطق جنوبی ایران و پایداری و ایثار مردمی که خانه‌هایشان در آتشفشان جنگ سوخت.",
    },
    {
        "id": 90032,
        "title": "دختر شینا",
        "author": "بهناز ضرابی‌زاده",
        "genre": "nonfiction, memoir, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388836603i/2274502.jpg",
        "avg_rating": 4.4,
        "description": "خاطرات صمیمی و صریح قدم‌خیر محمدی‌کنعان، همسر شهید ستار ابراهیمی؛ روایتی انسان‌محور از صبوری، عاشقانه زیستن و بزرگ کردن فرزندان در بحبوحه جنگ.",
    },
    {
        "id": 90033,
        "title": "دا",
        "author": "زهرا حسینی",
        "genre": "nonfiction, memoir, war",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918393i/6483489.jpg",
        "avg_rating": 4.7,
        "description": "خاطرات تکان‌دهنده سیده زهرا حسینی از روزهای آغازین سقوط خرمشهر؛ پرفروش‌ترین کتاب مستند جنگ که جانفشانی، درد و ایستادگی مقاومت شعبی را ثبت کرده است.",
    },
    {
        "id": 90034,
        "title": "پایی که جا ماند",
        "author": "سید ناصر حسینی‌پور",
        "genre": "nonfiction, memoir, war",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1344421111i/15809071.jpg",
        "avg_rating": 4.6,
        "description": "یادداشت‌های مخفیانه سید ناصر حسینی‌پور در تک مجنون و دوران اسارت در اردوگاه‌های مخفی عراق؛ سندی زنده از روحیه تسلیم‌ناپذیر اسرا.",
    },
    {
        "id": 90035,
        "title": "سلام بر ابراهیم",
        "author": "گروه فرهنگی شهید ابراهیم هادی",
        "genre": "nonfiction, biography, war",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1429813958i/25414161.jpg",
        "avg_rating": 4.5,
        "description": "زندگینامه و ۵۰ خاطره اثرگذار از پهلوان شهید ابراهیم هادی؛ روایتی از گمنامی، مرام پهلوانی، اخلاق و فداکاری‌هایش در جبهه‌های غرب و فکه.",
    },
    {
        "id": 90036,
        "title": "خاطرات یک مترجم",
        "author": "حسن شهیدی",
        "genre": "nonfiction, memoir, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388836604i/2274503.jpg",
        "avg_rating": 4.1,
        "description": "یادداشت‌های اتوبیوگرافیک و فرهنگی حسن شهیدی از فراز و نشیب‌های حرفه ترجمه، مواجهه با آثار بزرگ ادبیات جهان و زندگی در میان مطبوعات ایرانی.",
    },
    {
        "id": 90037,
        "title": "از چیزهای دیگر",
        "author": "محمدعلی موحد",
        "genre": "nonfiction, essays, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388836605i/2274504.jpg",
        "avg_rating": 4.3,
        "description": "مجموعه گفتارها و مقالات پژوهشی استاد محمدعلی موحد درباره عرفان ایرانی، تاریخ معاصر، ادبیات فاخر فارسی و اندیشمندان بزرگ.",
    },
    {
        "id": 90038,
        "title": "خواب آشفته نفت",
        "author": "محمدعلی موحد",
        "genre": "nonfiction, history, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388836606i/2274505.jpg",
        "avg_rating": 4.4,
        "description": "پژوهش جامع و تاریخ‌نگاری مستند ۴ جلدی محمدعلی موحد درباره دکتر مصدق، ملی شدن صنعت نفت و مداخلات قدرت‌های خارجی در حقوق ملت ایران.",
    },
    {
        "id": 90039,
        "title": "تاریخ ایران باستان",
        "author": "حسن پیرنیا",
        "genre": "history, nonfiction, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918394i/6098052.jpg",
        "avg_rating": 4.2,
        "description": "اثر ماندگار و مرجع حسن پیرنیا (مشیرالدوله)؛ تحلیلی جامع و کلاسیک از تاریخ ایران از مادها و هخامنشیان تا پایان دوران اشکانی و ساسانی.",
    },
    {
        "id": 90040,
        "title": "تاریخ تمدن ایران ساسانی",
        "author": "شاپور شهبازی",
        "genre": "history, nonfiction, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388836607i/2274506.jpg",
        "avg_rating": 4.3,
        "description": "بررسی باستان‌شناختی و تاریخی عمیق دکتر علیرضا شاپور شهبازی از ساختار اجتماعی، هنر، دین، ارتش و تمدن شاهنشاهی ساسانیان.",
    },
    {
        "id": 90041,
        "title": "ایران بین دو انقلاب",
        "author": "یرواند آبراهامیان",
        "genre": "history, nonfiction, political",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918395i/1858719.jpg",
        "avg_rating": 4.5,
        "description": "تحلیل جامعه‌شناختی و تاریخی کلاسیک یرواند آبراهامیان از ساختارهای سیاسی و گروه‌های اجتماعی ایران از انقلاب مشروطه تا انقلاب اسلامی.",
    },
    {
        "id": 90042,
        "title": "کتاب اعترافات",
        "author": "ژان-ژاک روسو",
        "genre": "nonfiction, memoir, philosophy",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388225217i/802263.jpg",
        "avg_rating": 4.1,
        "description": "ترجمه فارسی اتوبیوگرافی بی‌پروا و بنیان‌افکن ژان-ژاک روسو؛ اثری شگفت‌انگیز در افشای اندیشه‌ها، احساسات و خطایای شخصی یک فیلسوف بزرگ.",
    },
    {
        "id": 90043,
        "title": "قلعه حیوانات",
        "author": "جورج اورول",
        "genre": "fiction, political-satire, classics",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1424037542i/7613.jpg",
        "avg_rating": 4.6,
        "description": "شاهکار تمثیلی جرج اورول درباره شورش حیوانات مزرعه علیه انسان‌ها و انحراف آرمان‌های انقلابی به دیکتاتوری مطلق توسط خوک‌ها.",
    },
    {
        "id": 90044,
        "title": "۱۹۸۴",
        "author": "جورج اورول",
        "genre": "fiction, dystopian, classics",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1348990566i/5470.jpg",
        "avg_rating": 4.7,
        "description": "رمان دیستوپیایی برجسته جرج اورول درباره حکومت توتالیتر «برادر بزرگ»، نظارت همه‌جانبه، حذف حقیقت و تلاش وینستون اسمیت برای شرف و عشق.",
    },
    {
        "id": 90045,
        "title": "صد سال تنهایی",
        "author": "گابریل گارسیا مارکز",
        "genre": "fiction, magical-realism, classics",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327881361i/320.jpg",
        "avg_rating": 4.6,
        "description": "شاهکار رئالیسم جادویی گابریل گارسیا مارکز؛ داستان شش نسل از خانواده بوئندیا در دهکده خیالی ماکوندو که با تنهایی، عشق و جادو عجین شده است.",
    },
    {
        "id": 90046,
        "title": "عشق سال‌های وبا",
        "author": "گابریل گارسیا مارکز",
        "genre": "fiction, romance, magical-realism",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327124987i/9712.jpg",
        "avg_rating": 4.4,
        "description": "روایت باشکوه مارکز از عشق پرشور و صبورانه فلورنتینو آریزا به فرمینا دازا؛ عشقی که بیش از نیم قرن و در دوران همه‌گیری وبا زنده می‌ماند.",
    },
    {
        "id": 90047,
        "title": "کیمیاگر",
        "author": "پائولو کوئیلو",
        "genre": "fiction, philosophy, inspirational",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1483412266i/865.jpg",
        "avg_rating": 4.2,
        "description": "داستان الهام‌بخش سانتیاگو، چوپان جوان اندلسی که در جستجوی گنجی مادی روانه اهرام مصر می‌شود اما الگوی «حدیث خویشتن» و عرفان زندگی را می‌یابد.",
    },
    {
        "id": 90048,
        "title": "ملت عشق",
        "author": "الیف شافاک",
        "genre": "fiction, historical-fiction, romance",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1451446316i/21853621.jpg",
        "avg_rating": 4.5,
        "description": "رمانی دوگانه و پرفروش از الیف شافاک که روایت زندگی زنی معاصر را با ملاقات تاریخی شمس تبریزی و مولانا و چهل قاعده عشق پیوند می‌دهد.",
    },
    {
        "id": 90049,
        "title": "جزء از کل",
        "author": "استیو تولتز",
        "genre": "fiction, humor, contemporary",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1358276407i/48855.jpg",
        "avg_rating": 4.4,
        "description": "رمانی فلسفی، پرطنز و پرکشش از استیو تولتز درباره رابطه پدر و پسری عجیب (مارتین و جسپر دین) و تحلیل طنزآمیز جنون، مرگ و فجایع بشری.",
    },
    {
        "id": 90050,
        "title": "انسان در جستجوی معنا",
        "author": "ویکتور فرانکل",
        "genre": "nonfiction, psychology, philosophy",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1467136625i/4069.jpg",
        "avg_rating": 4.7,
        "description": "اثر روان‌شناختی روان‌پزشک اتریشی ویکتور فرانکل درباره تجربیاتش در اردوگاه‌های کار اجباری نازی‌ها و معرفی مکتب لوگودرمانی (معنادرمانی).",
    },
    {
        "id": 90051,
        "title": "دیوان حافظ",
        "author": "حافظ شیرازی",
        "genre": "poetry, persian-literature, classics",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918396i/2274507.jpg",
        "avg_rating": 4.9,
        "description": "مجموعه غزلیات لسان‌الغیب حافظ شیرازی؛ اوج عرفان، عشق، رندی و هنر کلام در ادبیات فارسی که بر تارک شعر جهان می‌درخشد.",
    },
    {
        "id": 90052,
        "title": "مثنوی معنوی",
        "author": "مولانا جلال‌الدین رومی",
        "genre": "poetry, persian-literature, mysticism",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918397i/2274508.jpg",
        "avg_rating": 4.9,
        "description": "شاهکار شش دفتر عرفان اسلامی و حکمت انسانی از مولانا؛ حکایات و آموزه‌های عمیقی که روح انسان را به مبدأ هستی متصل می‌سازد.",
    },
    {
        "id": 90053,
        "title": "گلستان",
        "author": "سعدی شیرازی",
        "genre": "poetry, persian-literature, classics",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918398i/2274509.jpg",
        "avg_rating": 4.8,
        "description": "اثر بی‌نظیر سعدی به نثر مسجع و منظوم در هشت باب؛ گنجینه‌ای از حکمت‌های اخلاقی، تعاملات انسانی و جهان‌بینی شیرین استاد سخن.",
    },
    {
        "id": 90054,
        "title": "بوستان",
        "author": "سعدی شیرازی",
        "genre": "poetry, persian-literature, classics",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918399i/2274510.jpg",
        "avg_rating": 4.7,
        "description": "مثنوی اخلاقی سعدی در ده باب از عدل، احسان، عشق، تواضع و قناعت؛ آرمان‌شهری که استاد سخن سعدی شیرازی برای آگاهی بشر سروده است.",
    },
    {
        "id": 90055,
        "title": "شاهنامه",
        "author": "فردوسی",
        "genre": "poetry, epic, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918400i/2274511.jpg",
        "avg_rating": 4.9,
        "description": "حماسه ملی و ماندگار فردوسی بزرگ در ۵۰ هزار بیت؛ شناسنامه هویت، زبان، اساطیر و تاریخ ایران از پیشدادیان تا غروب ساسانیان.",
    },
    {
        "id": 90056,
        "title": "خمسه",
        "author": "نظامی گنجوی",
        "genre": "poetry, persian-literature, classics",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918401i/2274512.jpg",
        "avg_rating": 4.8,
        "description": "پنج گنج نظامی گنجوی شامل مخزن‌الاسرار، خسرو و شیرین، لیلی و مجنون، هفت‌پیکر و اسکندرنامه؛ قله داستان‌سرایی منظوم فارسی.",
    },
    {
        "id": 90057,
        "title": "لیلی و مجنون",
        "author": "نظامی گنجوی",
        "genre": "poetry, romance, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918402i/2274513.jpg",
        "avg_rating": 4.7,
        "description": "روایت سوزناک نظامی گنجوی از عشق جنون‌آمیز قیس عامری (مجنون) و لیلی؛ روایتی سرشار از سمبل‌های عرفانی و زیبایی‌های کلامی.",
    },
    {
        "id": 90058,
        "title": "خسرو و شیرین",
        "author": "نظامی گنجوی",
        "genre": "poetry, romance, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918403i/2274514.jpg",
        "avg_rating": 4.7,
        "description": "داستان عاشقانه و تاریخی خسروپرویز شاه ساسانی، شیرین شاهزاده ارمنستان و فداکاری فرهاد تراشکار با سروده‌ای دلکش از نظامی.",
    },
    {
        "id": 90059,
        "title": "منطق‌الطیر",
        "author": "عطار نیشابوری",
        "genre": "poetry, mysticism, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918404i/2274515.jpg",
        "avg_rating": 4.8,
        "description": "مثنوی عرفانی و تمثیلی عطار نیشابوری درباره سفر سی مرغ از هفت وادی سلوک برای رسیدن به سیمرغ و درک حقیقت وحدت وجود.",
    },
    {
        "id": 90060,
        "title": "تذکرة الاولیا",
        "author": "عطار نیشابوری",
        "genre": "nonfiction, mysticism, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918405i/2274516.jpg",
        "avg_rating": 4.6,
        "description": "شرح حال شگفت‌انگیز و نثر صوفیانه عطار درباره حالات، سخنان و کرامات ۹۶ تن از مشایخ و اولیای بزرگ عرفان اسلامی.",
    },
    {
        "id": 90061,
        "title": "مصیبت‌نامه",
        "author": "عطار نیشابوری",
        "genre": "poetry, mysticism, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918406i/2274517.jpg",
        "avg_rating": 4.5,
        "description": "مثنوی عمیق عطار درباره سیر روح سالک در میان موجودات و فرشتگان در طلب حقیقت و دست یافتن به فقر و فنای فی‌الله.",
    },
    {
        "id": 90062,
        "title": "دیوان شمس",
        "author": "مولانا جلال‌الدین رومی",
        "genre": "poetry, mysticism, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918407i/2274518.jpg",
        "avg_rating": 4.8,
        "description": "دیوان کبیر غزلیات شورانگیز مولانا که در وجد سماع و تحت تأثیر اشتیاق شمس تبریزی سروده شده است؛ فوران عشق و موسیقی کلام.",
    },
    {
        "id": 90063,
        "title": "فیه ما فیه",
        "author": "مولانا جلال‌الدین رومی",
        "genre": "nonfiction, mysticism, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918408i/2274519.jpg",
        "avg_rating": 4.6,
        "description": "مجموعه مکتوبات و سخنرانی‌های منثور مولانا که توسط مریدانش یادداشت شده و کلید درک آموزه‌های پیچیده مثنوی معنوی است.",
    },
    {
        "id": 90064,
        "title": "مکتوبات",
        "author": "مولانا جلال‌الدین رومی",
        "genre": "nonfiction, mysticism, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918409i/2274520.jpg",
        "avg_rating": 4.4,
        "description": "مجموعه نامه‌های واقعی مولانا به بزرگان، امرا و شاگردانش که روشنگر ابعاد اجتماعی، اخلاقی و زندگی روزمره این عارف نامی است.",
    },
    {
        "id": 90065,
        "title": "حدیقه الحقیقه",
        "author": "سنایی غزنوی",
        "genre": "poetry, mysticism, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918410i/2274521.jpg",
        "avg_rating": 4.5,
        "description": "نخستین منظومه بزرگ عرفانی و اخلاقی در ادبیات فارسی از حکیم سنایی غزنوی که سرچشمه الهام عطار و مولوی بوده است.",
    },
    {
        "id": 90066,
        "title": "مخزن‌الاسرار",
        "author": "نظامی گنجوی",
        "genre": "poetry, mysticism, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918411i/2274522.jpg",
        "avg_rating": 4.5,
        "description": "نخستین مثنوی از ۵ گنج نظامی در حدود ۲۲۰۰ بیت؛ منظومه‌ای اندیشمندانه در زهد، حکمت و اندرزهای انسانی همراه با حکایت‌های تمثیلی.",
    },
    {
        "id": 90067,
        "title": "ویس و رامین",
        "author": "فخرالدین اسعد گرگانی",
        "genre": "poetry, romance, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918412i/2274523.jpg",
        "avg_rating": 4.4,
        "description": "منظومه عاشقانه کهن ایرانی متعلق به دوران اشکانیان که با زبان شاداب فخرالدین اسعد گرگانی، روایتگر عشق پرفراز و نشیب ویس و رامین است.",
    },
    {
        "id": 90068,
        "title": "کلیله و دمنه",
        "author": "نصرالله منشی",
        "genre": "fiction, fable, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918413i/2274524.jpg",
        "avg_rating": 4.6,
        "description": "مجموعه حکایات حکمت‌آموز تمثیلی از زبان حیوانات (به‌ویژه دو شغال کلیله و دمنه) با ترجمه منثور فاخر نصرالله منشی در سیاست و اخلاق.",
    },
    {
        "id": 90069,
        "title": "تاریخ بیهقی",
        "author": "ابوالفضل بیهقی",
        "genre": "history, nonfiction, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918414i/2274525.jpg",
        "avg_rating": 4.7,
        "description": "شاهکار نثر کهن فارسی و گزارش بی‌طرفانه ابوالفضل بیهقی از دربار غزنویان؛ روایتی درخشان، دراماتیک و انسانی از عزل و نصب‌ها و حوادث تاریخی.",
    },
    {
        "id": 90070,
        "title": "سیاست‌نامه",
        "author": "خواجه نظام‌الملک طوسی",
        "genre": "nonfiction, political, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918415i/2274526.jpg",
        "avg_rating": 4.5,
        "description": "سیرالملوک خواجه نظام‌الملک طوسی، وزیر مدبر سلجوقیان؛ اندرزنامه‌ای منثور در ۵۰ فصل درباره آیین کشورداری، دادرسی و شیوه حکمرانی.",
    },
    {
        "id": 90071,
        "title": "قابوس‌نامه",
        "author": "عنصرالمعالی کیکاوس",
        "genre": "nonfiction, ethics, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918416i/2274527.jpg",
        "avg_rating": 4.4,
        "description": "پندنامه کاربردی و صمیمی عنصرالمعالی برای فرزندش گیلان‌شاه در ۴۴ باب؛ راهنمایی روان درباره اخلاق زندگی، حرفه‌ها و تعاملات اجتماعی.",
    },
    {
        "id": 90072,
        "title": "اخلاق ناصری",
        "author": "خواجه نصیرالدین طوسی",
        "genre": "nonfiction, philosophy, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918417i/2274528.jpg",
        "avg_rating": 4.5,
        "description": "مهم‌ترین متن فلسفه اخلاق و حکمت عملی در ادبیات فارسی از خواجه نصیرالدین طوسی در سه بخش: تهذیب اخلاق، تدبیر منزل و سیاست مدن.",
    },
    {
        "id": 90073,
        "title": "اسرارالتوحید",
        "author": "محمد بن منور",
        "genre": "nonfiction, mysticism, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918418i/2274529.jpg",
        "avg_rating": 4.6,
        "description": "اسرارالتوحید فی مقامات الشیخ ابی‌سعید؛ روایتی دلنشین از زندگی، حالات، کرامات و سخنان عارف بزرگ بوسعید ابوالخیر از زبان نواده‌اش.",
    },
    {
        "id": 90074,
        "title": "کشف‌المحجوب",
        "author": "علی بن عثمان هجویری",
        "genre": "nonfiction, mysticism, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918419i/2274530.jpg",
        "avg_rating": 4.5,
        "description": "نخستین کتاب جامع و منظم به زبان فارسی در شرح اصول تصوف، اصطلاحات عرفانی و زندگینامه مشایخ صوفیه اثر علی بن عثمان هجویری.",
    },
    {
        "id": 90075,
        "title": "رساله قشیریه",
        "author": "عبدالکریم قشیری",
        "genre": "nonfiction, mysticism, persian-literature",
        "cover_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327918420i/2274531.jpg",
        "avg_rating": 4.4,
        "description": "متن کلاسیک و ارجمند تصوف اسلامی اثر ابوالقاسم قشیری با ترجمه کهن فارسی؛ شامل شرح اصطلاحات، مقامات و احوال عارفان بزرگ.",
    },
]


def seed_persian_books():
    conn = get_connection()
    cursor = conn.cursor()

    rows = [
        (
            b["id"],
            b["title"],
            b["author"],
            b["genre"],
            b["cover_url"],
            b["avg_rating"],
            b["description"],
        )
        for b in PERSIAN_BOOKS
    ]

    cursor.executemany(
        """INSERT OR REPLACE INTO books
           (id, title, author, genre, cover_url, avg_rating, description)
           VALUES (?, ?, ?, ?, ?, ?, ?)""",
        rows,
    )

    conn.commit()
    conn.close()
    print(f"Seeded {len(rows)} Persian books with covers and full descriptions.")


if __name__ == "__main__":
    seed_persian_books()